import Navbar from "@/components/header/navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Categories from "@/components/categories";
import MaxWidthWrapper from "@/components/max-width-wrapper";
import { ClerkProvider } from "@clerk/nextjs";
import { getCurrentUser } from "@/lib/current-user";
import ToastProvider from "@/providers/toast-provider";
import { cn } from "@/lib/utils";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={cn(inter.className, "bg-accent/50")}>
          <ToastProvider />
          <Navbar currentUser={currentUser} />
          <MaxWidthWrapper className="pt-[80px] h-full">
            {children}
          </MaxWidthWrapper>
        </body>
      </html>
    </ClerkProvider>
  );
}
