import Footer from "@/components/footer";
import Header from "@/components/header/header";
import { getCurrentUser } from "@/lib/current-user";
import { cn } from "@/lib/utils";
import ModalProvider from "@/providers/modal-provider";
import { QueryProvider } from "@/providers/query-provider";
import ToastProvider from "@/providers/toast-provider";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={cn(
            inter.className,
            "absolute inset-0 overflow-y-hidden -z-10 w-full bg-white bg-[linear-gradient(to_right,#8080800a_1px,transparent_1px),linear-gradient(to_bottom,#8080800a_1px,transparent_1px)] bg-[size:14px_24px]"
          )}
        >
          <div className="fixed left-0 right-0 top-0 -z-10 m-auto h-[310px] w-[310px] rounded-full bg-rose-400 opacity-20 blur-[100px]" />
          <div className=" overflow-y-auto h-full flex flex-col gap-5 min-h-screen">
            <QueryProvider>
              <ModalProvider />
              <ToastProvider />
              <Header currentUser={currentUser} />
              <main className="flex-grow flex-1">{children}</main>
              <Footer />
            </QueryProvider>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
